### ISSUE TITLE
Error on preprocess.py: 'The directory name is invalid: '

### ISSUE THREAD

**Issue by t2ac32** [jonnor/ESC-CNN-microcontroller#3]
For some reason after all files are download when running preprocess.py
this error is triggered:

The directory name is invalid: './data/features\\mels:augmentations=12,fmax=11025,fmin=0,hop_length=512,n_fft=1024,n_mels=60,samplerate=22050'

**Comment by jonnor** [comment]
Hi @t2ac32 ! What operating system, and file system do you use?

**Comment by yacaeh** [comment]
Same issue here with Windows10

**Comment by t2ac32** [comment]
> Hi @t2ac32 ! What operating system, and file system do you use?

Windows 10
