### ISSUE TITLE
Question for source

### ISSUE THREAD

**Issue by Wind010321** [jonnor/ESC-CNN-microcontroller#4]
I want to reproduce the project by myself. But I have some confusion in the model deployment. Is there a video to teach how to do in the website?

**Comment by jonnor** [comment]
Hi @Wind010321 - you mean deployment to microcontroller? That is done using the official ST tools X-CUBE-AI. They have several pieces of audio example code that the model can be integrated in, see https://www.st.com/en/embedded-software/x-cube-ai.html documentation.
Unfortunately I do not have any more specific documentation or ready to run open source code for that. 

Our commercial devices at https://soundsensing.no have on-device classification capabilities for noise classes (building on other datasets than US8k), if that could be of interest.

**Comment by Wind010321** [comment]
I‘ll try that. Thanks for a lot!
