### ISSUE TITLE
What's your method to show that the sensortile is getting the sound signal?

### ISSUE THREAD

**Issue by Wind010321** [jonnor/ESC-CNN-microcontroller#5]

**Comment by Wind010321** [comment]
Hello, Please share your method to show that the sensortile is getting the sound signal?  Is it through a software or a website...?

**Comment by jonnor** [comment]
Hi @Wind010321 - what do you refer to by "show that the sensor tile is getting the sound signal"?

**Comment by Wind010321** [comment]
Hi, @jonnor - It takes me a long time to solve some hardware problems.
